name: DumprX

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Firmware Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TZ: Asia/Kolkata

jobs:
  Firmware-Dump:
      runs-on: ubuntu-20.04

      steps:

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main 

      - name: Cloning DumprX
        run: |
             git clone --depth=1 https://github.com/JaswantTeja/Dumper-Script dumper

      - name: Installing Requirements
        run: |
             cd dumper
             chmod a+x setup.sh
             bash setup.sh

      - name: Firmware is Dumping
        run: |
             cd dumper
             chmod a+x dumprx.sh
             echo "Jaswant-Dumpyard" > .github_orgname
             echo "${{ secrets.GIT_TOKEN }}" > .github_token
             bash dumprx.sh $LINK
